/*
 * Copyright 2001-2016 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_URI_H
# define HEADER_URI_H

# ifdef  __cplusplus
extern "C" {
# endif

int OPENSSL_decode_uri(const char *uri, char **scheme, char **authority,
                       char **path, char **query, char **fragment);

/* BEGIN ERROR CODES */
/*
 * The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */

int ERR_load_URI_strings(void);

/* Error codes for the URI functions. */

/* Function codes. */
# define URI_F_EXTRACT_AUTHORITY                          100
# define URI_F_EXTRACT_FRAGMENT                           101
# define URI_F_EXTRACT_PATH_ABEMPTY                       102
# define URI_F_EXTRACT_PATH_ABSOLUTE                      103
# define URI_F_EXTRACT_PATH_EMPTY                         104
# define URI_F_EXTRACT_PATH_NOSCHEME                      105
# define URI_F_EXTRACT_PATH_ROOTLESS                      106
# define URI_F_EXTRACT_QUERY                              107
# define URI_F_EXTRACT_SCHEME                             108
# define URI_F_OPENSSL_DECODE_URI                         109

/* Reason codes. */
# define URI_R_FAILED_TO_DECODE_URI                       100
# define URI_R_INVALID_CHARACTER_IN_URI                   101
# define URI_R_MALFORMED_HOST_IN_URI                      102
# define URI_R_MALFORMED_PATH_IN_URI                      103

# ifdef  __cplusplus
}
# endif
#endif
